"""cambios

Revision ID: f05394748a36
Revises: 
Create Date: 2025-12-21 19:28:27.113161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f05394748a36'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('banco',
    sa.Column('id_banco', sa.Integer(), nullable=False),
    sa.Column('nombre_banco', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id_banco')
    )
    op.create_table('categoria_finanza',
    sa.Column('id_categoria', sa.BigInteger(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id_categoria'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('categoria_habito',
    sa.Column('id_categoria', sa.BigInteger(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id_categoria')
    )
    op.create_table('libros',
    sa.Column('id_libro', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre_libro', sa.String(), nullable=False),
    sa.Column('nombre_autor', sa.String(), nullable=False),
    sa.Column('total_paginas', sa.String(), nullable=False),
    sa.Column('categoria', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id_libro'),
    sa.UniqueConstraint('nombre_libro')
    )
    op.create_table('usuario',
    sa.Column('id_usuario', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('telefono', sa.String(length=12), nullable=False),
    sa.Column('activo', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('fecha_registro', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id_usuario'),
    sa.UniqueConstraint('telefono')
    )
    op.create_table('cuenta_bancaria',
    sa.Column('id_cuenta', sa.BigInteger(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_banco', sa.Integer(), nullable=False),
    sa.Column('nombre_cuenta', sa.String(length=100), nullable=False),
    sa.Column('tipo_cuenta', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['id_banco'], ['banco.id_banco'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_cuenta')
    )
    op.create_table('entrenamiento',
    sa.Column('id_entrenamiento', sa.BigInteger(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('subtipo', sa.String(length=50), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('observacion', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_entrenamiento')
    )
    op.create_table('habito',
    sa.Column('id_habito', sa.BigInteger(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_categoria', sa.BigInteger(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('frecuencia', sa.String(length=50), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_categoria'], ['categoria_habito.id_categoria'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_habito')
    )
    op.create_table('lectura',
    sa.Column('id_lectura', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_libro', sa.Integer(), nullable=False),
    sa.Column('fecha_inicio', sa.DateTime(), nullable=False),
    sa.Column('fecha_fin', sa.DateTime(), nullable=True),
    sa.Column('estado', sa.Enum('terminado', 'en_proceso', 'abandonado', 'sin_comenzar', name='estadolectura'), server_default='sin_comenzar', nullable=False),
    sa.ForeignKeyConstraint(['id_libro'], ['libros.id_libro'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_lectura')
    )
    op.create_table('mensaje',
    sa.Column('id_mensaje', sa.BigInteger(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('contenido', sa.Text(), nullable=False),
    sa.Column('direccion', sa.String(length=50), nullable=False),
    sa.Column('fecha_envio', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_mensaje')
    )
    op.create_table('entrenamiento_aerobico',
    sa.Column('id_aerobico', sa.BigInteger(), nullable=False),
    sa.Column('id_entrenamiento', sa.BigInteger(), nullable=False),
    sa.Column('distancia_km', sa.DECIMAL(precision=5, scale=2), nullable=False),
    sa.Column('duracion', sa.Time(), nullable=False),
    sa.Column('ritmo_promedio', sa.DECIMAL(precision=5, scale=2), nullable=False),
    sa.Column('calorias', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_entrenamiento'], ['entrenamiento.id_entrenamiento'], ),
    sa.PrimaryKeyConstraint('id_aerobico')
    )
    op.create_table('entrenamiento_fuerza',
    sa.Column('id_fuerza', sa.BigInteger(), nullable=False),
    sa.Column('id_entrenamiento', sa.BigInteger(), nullable=False),
    sa.Column('musculo_principal', sa.String(length=100), nullable=False),
    sa.Column('rutina', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['id_entrenamiento'], ['entrenamiento.id_entrenamiento'], ),
    sa.PrimaryKeyConstraint('id_fuerza')
    )
    op.create_table('registro_habito',
    sa.Column('id_registro', sa.BigInteger(), nullable=False),
    sa.Column('id_habito', sa.BigInteger(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('observacion', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id_habito'], ['habito.id_habito'], ),
    sa.PrimaryKeyConstraint('id_registro')
    )
    op.create_table('registro_lectura',
    sa.Column('id_registro', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('id_lectura', sa.BigInteger(), nullable=False),
    sa.Column('pagina_inicio', sa.Integer(), nullable=False),
    sa.Column('pagina_final', sa.Integer(), nullable=False),
    sa.Column('observacion', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_lectura'], ['lectura.id_lectura'], ),
    sa.PrimaryKeyConstraint('id_registro')
    )
    op.create_table('transaccion_finanza',
    sa.Column('id_transaccion', sa.BigInteger(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_categoria', sa.BigInteger(), nullable=False),
    sa.Column('id_cuenta', sa.BigInteger(), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('monto', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_categoria'], ['categoria_finanza.id_categoria'], ),
    sa.ForeignKeyConstraint(['id_cuenta'], ['cuenta_bancaria.id_cuenta'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_transaccion')
    )
    op.create_table('ejercicio',
    sa.Column('id_ejercicio', sa.BigInteger(), nullable=False),
    sa.Column('id_fuerza', sa.BigInteger(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('series', sa.Integer(), nullable=False),
    sa.Column('repeticiones', sa.Integer(), nullable=False),
    sa.Column('peso_kg', sa.DECIMAL(precision=5, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['id_fuerza'], ['entrenamiento_fuerza.id_fuerza'], ),
    sa.PrimaryKeyConstraint('id_ejercicio')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ejercicio')
    op.drop_table('transaccion_finanza')
    op.drop_table('registro_lectura')
    op.drop_table('registro_habito')
    op.drop_table('entrenamiento_fuerza')
    op.drop_table('entrenamiento_aerobico')
    op.drop_table('mensaje')
    op.drop_table('lectura')
    op.drop_table('habito')
    op.drop_table('entrenamiento')
    op.drop_table('cuenta_bancaria')
    op.drop_table('usuario')
    op.drop_table('libros')
    op.drop_table('categoria_habito')
    op.drop_table('categoria_finanza')
    op.drop_table('banco')
    # ### end Alembic commands ###
